services:
  nvim:
    image: neovim:0.0.8
    container_name: nvim
    volumes:
      - /opt/ContainerProjects:/projects
      - $HOME/.ssh:/home/nvim/.ssh
    working_dir: /projects
    network_mode: "host"
    cpus: 1
    mem_limit: 1g
