services:
  nvim-go:
    image: neovim-go:0.0.2
    container_name: nvim-go
    volumes:
      - /opt/ContainerProjects:/projects
      - $HOME/.ssh:/home/nvim/.ssh
    working_dir: /projects
    network_mode: "host"
    cpus: 1
    mem_limit: 1g
